import { useAppDispatch, useAppSelector } from "./hooks";

import {
  setLogInModal,
  setSignUpModal,
  setAssignedView,
  enableLogInModal,
  enableSignUpModal,
  enableAssignedView,
  setCreateTransactionModal,
  enableCreateTransactionModal,
  setAddCardModal,
  enableAddCardModal,
  setRemoveCardModal,
  enableRemoveCardModal,
  setDepositBalanceModal,
  enableDepositBalanceModal,
  setWithdrawlBalanceModal,
  enableWithdrawlBalanceModal,
  setForgotPasswordModal,
  enableForgotPasswordModal,
  setQrLogInModal,
  enableQrLogInModal,
  setResetPasswordModal,
  enableResetPasswordModal,
} from "./slices";

import { store } from "./store";

export {
  setLogInModal,
  setSignUpModal,
  setAssignedView,
  enableLogInModal,
  enableSignUpModal,
  enableAssignedView,
  setCreateTransactionModal,
  enableCreateTransactionModal,
  useAppDispatch,
  useAppSelector,
  store,
  setAddCardModal,
  enableAddCardModal,
  setRemoveCardModal,
  enableRemoveCardModal,
  setDepositBalanceModal,
  enableDepositBalanceModal,
  setWithdrawlBalanceModal,
  enableWithdrawlBalanceModal,
  setForgotPasswordModal,
  enableForgotPasswordModal,
  setQrLogInModal,
  enableQrLogInModal,
  setResetPasswordModal,
  enableResetPasswordModal,
};
